#!/bin/zsh

set -e

cp .zshrc ~
cp .gitconfig ~/

# setup git autocompletion
mkdir -p ~/.zsh
cp git-completion.bash _git ~/.zsh

source ~/.zshrc

for x in install-*.sh; do
 sh -c "./${x}"
done

chsh -s /bin/zsh

mkdir -p ~/src

# Run macOS defaults configuration
./macos_defaults.sh
